title: RDB
description: The ultimate ORM for Node and Typescript
image: "/docs/logo-sm.jpg"
url: "https://rdbjs.org" 
logo: "/docs/logo-sm.jpg"

markdown: GFM
remote_theme: pages-themes/primer@v0.2.0
plugins:
  - jekyll-seo-tag