title: RDB - The ultimate ORM for Node and Typescript
url: "https://rdbjs.org" 
description: The most developer friendly ORM ever. Fetch rows directly in the browser in a safe manner. Powerful filtering. Change detection and concurrency handling.
image: "/docs/logo-sm.jpg"

markdown: GFM
theme: minima
# plugins:
