title: The ultimate ORM for Node and Typescript
url: "https://orange-orm.org" 
description: The most developer friendly ORM ever. Fetch rows directly in the browser in a safe manner. Powerful filtering. Change detection and concurrency handling.
image: "/docs/orange.svg"

markdown: GFM
theme: minima
# plugins:
