import bodyParser from 'body-parser';
import cors from 'cors';
import express from 'express';
import { createRequire } from 'node:module';
import { createDemoMap, syncTables } from '../../shared/schema.js';

const require = createRequire(import.meta.url);
const rdb = require('../../../src/index.js');
const { setupChangeTracking } = require('../../../src/sync/setupChangeTracking.js');
const port = Number(process.env.PORT || 3055);
const connectionString = process.env.DATABASE_URL || 'postgres://orange:orange@localhost:54329/orange_sync_demo';

const map = createDemoMap(rdb);
const db = map({
  db: (con) => con.pg(connectionString, { size: 4 })
});

await initDatabase();

const app = express();
app.use(cors({
  origin: ['http://localhost:5173', 'http://127.0.0.1:5173'],
  credentials: false
}));
app.use(bodyParser.json({ limit: '5mb' }));

app.get('/health', (_req, res) => {
  res.json({ ok: true });
});

app.get('/api/snapshot', async (_req, res, next) => {
  try {
    const projects = await db.project.getAll({
      owner: { team: {} },
      detail: {},
      tasks: { assignee: {} }
    });
    res.json({ projects });
  }
  catch (e) {
    next(e);
  }
});

app.post('/api/seed-server-change', async (_req, res, next) => {
  try {
    const firstTask = await db.task.getOne(undefined, { orderBy: 'id' });
    if (firstTask) {
      firstTask.title = `${firstTask.title.replace(/ \(server\)$/u, '')} (server)`;
      await firstTask.saveChanges();
    }
    res.json({ ok: true });
  }
  catch (e) {
    next(e);
  }
});

app.use('/rdb', db.express({
  sync: {
    queue: { concurrency: 1, maxPending: 100 },
    limits: {
      maxTablesPerRequest: 20,
      maxKeysPerBatch: 50,
      maxRowsPerBatch: 50,
      maxChangeWindow: 500
    }
  }
}));

app.use((err, _req, res, _next) => {
  res.status(err.status || 500).json({
    error: err.message || String(err)
  });
});

app.listen(port, () => {
  console.log(`Orange sync demo backend listening on http://localhost:${port}`);
});

async function initDatabase() {
  await runStatements(db, schemaSql);
  await setupChangeTracking(db, pickTables(db.tables, syncTables));
  await seedIfEmpty();
}

async function seedIfEmpty() {
  const rows = await db.query('select count(*)::int as count from team');
  if (Number(rows[0]?.count || 0) > 0)
    return;

  const platform = await db.team.insert({ name: 'Platform' });
  const product = await db.team.insert({ name: 'Product' });
  const ada = await db.person.insert({ teamId: platform.id, name: 'Ada Lovelace', email: 'ada@example.test' });
  const grace = await db.person.insert({ teamId: product.id, name: 'Grace Hopper', email: 'grace@example.test' });

  const syncProject = await db.project.insert({
    ownerId: ada.id,
    title: 'Offline sync rollout',
    status: 'active',
    updatedAt: new Date(),
    detail: {
      summary: 'Exercise push, pull, references, hasOne and hasMany relations.',
      riskLevel: 'medium'
    },
    tasks: [
      { assigneeId: ada.id, title: 'Capture local patches', done: true, sortOrder: 1 },
      { assigneeId: grace.id, title: 'Replay mutations on server', done: false, sortOrder: 2 }
    ]
  });

  await db.project.insert({
    ownerId: grace.id,
    title: 'OPFS browser client',
    status: 'planning',
    updatedAt: new Date(),
    detail: {
      summary: 'Use sqliteOPFS as the local durable browser database.',
      riskLevel: 'low'
    },
    tasks: [
      { assigneeId: grace.id, title: 'Verify worker-backed SQLite', done: false, sortOrder: 1 }
    ]
  });
}

function pickTables(tables, names) {
  return Object.fromEntries(names.map((name) => [name, tables[name]]));
}

async function runStatements(targetDb, sql) {
  for (const statement of sql.split(';')) {
    if (statement.trim())
      await targetDb.query(statement);
  }
}

const schemaSql = `
create table if not exists team (
  id integer generated by default as identity primary key,
  name text not null
);

create table if not exists person (
  id integer generated by default as identity primary key,
  "teamId" integer not null references team(id),
  name text not null,
  email text
);

create table if not exists project (
  id integer generated by default as identity primary key,
  "ownerId" integer not null references person(id),
  title text not null,
  status text not null,
  "updatedAt" timestamptz
);

create table if not exists project_detail (
  id integer generated by default as identity primary key,
  "projectId" integer not null unique references project(id) on delete cascade,
  summary text,
  "riskLevel" text
);

create table if not exists task (
  id integer generated by default as identity primary key,
  "projectId" integer not null references project(id) on delete cascade,
  "assigneeId" integer references person(id),
  title text not null,
  done boolean default false,
  "sortOrder" integer
);
`;
