name: "Feature Request"
description: Suggest an idea for this project
title: "[ENHANCEMENT]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
