version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    # working_dir: /app
    volumes:
      - ..:/workspace:cached
      - try-node-node_modules:/workspace/node_modules
      # - ..:/usr/config
      # - /usr/config/node_modules
    # environment:
      # - ACCEPT_EULA=Y
      # - SA_PASSWORD=P@assword123
    depends_on: 
      - postgres
      - mssql
      - mysql
      - sapase
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 14332:5432
    # restart: always
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@assword123
    ports:
      - 14330:1433
    #restart: always
  mysql:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
    # restart: always
  sapase:
    image: larsroald/ase-server    
    hostname: sapase
    ports:
      - 50000:5000
    # restart: always
volumes:
  try-node-node_modules: