version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    # working_dir: /app
    # volumes:
    #   - ..:/workspace:cached
    # environment:
      # - ACCEPT_EULA=Y
      # - SA_PASSWORD=P@assword123
    depends_on: 
      - postgres      
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 54320:5432
    restart: always